// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fl
double fl(double x, Rcpp::String strDistr);
RcppExport SEXP _jwglm_fl(SEXP xSEXP, SEXP strDistrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type strDistr(strDistrSEXP);
    rcpp_result_gen = Rcpp::wrap(fl(x, strDistr));
    return rcpp_result_gen;
END_RCPP
}
// Fl
double Fl(double x, Rcpp::String strDistr);
RcppExport SEXP _jwglm_Fl(SEXP xSEXP, SEXP strDistrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type strDistr(strDistrSEXP);
    rcpp_result_gen = Rcpp::wrap(Fl(x, strDistr));
    return rcpp_result_gen;
END_RCPP
}
// Get_beta_only
arma::vec Get_beta_only(arma::vec beta, arma::vec Y, arma::mat X, arma::mat D, Rcpp::String strDistr, int nIter, double lr, double crit, bool bDisp);
RcppExport SEXP _jwglm_Get_beta_only(SEXP betaSEXP, SEXP YSEXP, SEXP XSEXP, SEXP DSEXP, SEXP strDistrSEXP, SEXP nIterSEXP, SEXP lrSEXP, SEXP critSEXP, SEXP bDispSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type D(DSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type strDistr(strDistrSEXP);
    Rcpp::traits::input_parameter< int >::type nIter(nIterSEXP);
    Rcpp::traits::input_parameter< double >::type lr(lrSEXP);
    Rcpp::traits::input_parameter< double >::type crit(critSEXP);
    Rcpp::traits::input_parameter< bool >::type bDisp(bDispSEXP);
    rcpp_result_gen = Rcpp::wrap(Get_beta_only(beta, Y, X, D, strDistr, nIter, lr, crit, bDisp));
    return rcpp_result_gen;
END_RCPP
}
// Get_bias
arma::vec Get_bias(arma::mat X, arma::mat D, arma::vec beta, Rcpp::String strDistr);
RcppExport SEXP _jwglm_Get_bias(SEXP XSEXP, SEXP DSEXP, SEXP betaSEXP, SEXP strDistrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type D(DSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type strDistr(strDistrSEXP);
    rcpp_result_gen = Rcpp::wrap(Get_bias(X, D, beta, strDistr));
    return rcpp_result_gen;
END_RCPP
}
// Find_MDBeta
List Find_MDBeta(arma::vec beta0, arma::vec Y, arma::mat X, arma::mat D, Rcpp::String strDistr, int nIter, double lr, double crit, bool bBias, bool bDisp);
RcppExport SEXP _jwglm_Find_MDBeta(SEXP beta0SEXP, SEXP YSEXP, SEXP XSEXP, SEXP DSEXP, SEXP strDistrSEXP, SEXP nIterSEXP, SEXP lrSEXP, SEXP critSEXP, SEXP bBiasSEXP, SEXP bDispSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type beta0(beta0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type D(DSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type strDistr(strDistrSEXP);
    Rcpp::traits::input_parameter< int >::type nIter(nIterSEXP);
    Rcpp::traits::input_parameter< double >::type lr(lrSEXP);
    Rcpp::traits::input_parameter< double >::type crit(critSEXP);
    Rcpp::traits::input_parameter< bool >::type bBias(bBiasSEXP);
    Rcpp::traits::input_parameter< bool >::type bDisp(bDispSEXP);
    rcpp_result_gen = Rcpp::wrap(Find_MDBeta(beta0, Y, X, D, strDistr, nIter, lr, crit, bBias, bDisp));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_jwglm_fl", (DL_FUNC) &_jwglm_fl, 2},
    {"_jwglm_Fl", (DL_FUNC) &_jwglm_Fl, 2},
    {"_jwglm_Get_beta_only", (DL_FUNC) &_jwglm_Get_beta_only, 9},
    {"_jwglm_Get_bias", (DL_FUNC) &_jwglm_Get_bias, 4},
    {"_jwglm_Find_MDBeta", (DL_FUNC) &_jwglm_Find_MDBeta, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_jwglm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
