# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Fl <- function(x, strDistr = "Logit") {
    .Call(`_jwglm_Fl`, x, strDistr)
}

Find_MDBeta <- function(beta0, Y, X, D, strDistr, nIter = 100L, lr = 0.01, crit = 1e-3, bBias = FALSE, bDisp = FALSE) {
    .Call(`_jwglm_Find_MDBeta`, beta0, Y, X, D, strDistr, nIter, lr, crit, bBias, bDisp)
}

